import type { CardDefinition } from '../types';

export const cards: Record<string, CardDefinition> = {
  strike: {
    id: 'strike',
    name: 'Strike',
    cost: 1,
    type: 'attack',
    description: 'Deal 5 damage.',
    effects: [{ type: 'damage', amount: 5 }],
    puzzleRoles: ['finisher'],
  },
  guard: {
    id: 'guard',
    name: 'Guard',
    cost: 1,
    type: 'defense',
    description: 'Gain 5 block.',
    effects: [{ type: 'block', amount: 5 }],
    puzzleRoles: ['counter', 'stabilizer'],
  },
  quickStep: {
    id: 'quickStep',
    name: 'Quick Step',
    cost: 0,
    type: 'utility',
    description: 'Draw 1 card.',
    effects: [{ type: 'draw', amount: 1 }],
    puzzleRoles: ['setup'],
  },
  villageTool: {
    id: 'villageTool',
    name: 'Village Tool',
    cost: 1,
    type: 'utility',
    description: 'Gain 3 block. Deal 3 damage.',
    effects: [
      { type: 'block', amount: 3 },
      { type: 'damage', amount: 3 },
    ],
    puzzleRoles: ['counter', 'finisher'],
  },
  ironStrike: {
    id: 'ironStrike',
    name: 'Iron Strike',
    cost: 1,
    type: 'attack',
    description: 'Deal 7 damage.',
    effects: [{ type: 'damage', amount: 7 }],
    unlock: { building: 'forge', level: 1 },
    puzzleRoles: ['finisher'],
  },
  temperShield: {
    id: 'temperShield',
    name: 'Temper Shield',
    cost: 1,
    type: 'defense',
    description: 'Gain 7 block.',
    effects: [{ type: 'block', amount: 7 }],
    unlock: { building: 'forge', level: 2 },
    puzzleRoles: ['counter', 'stabilizer'],
  },
  cleavingHook: {
    id: 'cleavingHook',
    name: 'Cleaving Hook',
    cost: 2,
    type: 'attack',
    description: 'Deal 11 damage.',
    effects: [{ type: 'damage', amount: 11 }],
    unlock: { building: 'forge', level: 2 },
    puzzleRoles: ['finisher'],
  },
  herbalPoultice: {
    id: 'herbalPoultice',
    name: 'Herbal Poultice',
    cost: 1,
    type: 'utility',
    description: 'Heal 5. Exhaust.',
    effects: [{ type: 'heal', amount: 5 }],
    exhaust: true,
    unlock: { building: 'herbalHut', level: 1 },
    puzzleRoles: ['stabilizer'],
  },
  rotknife: {
    id: 'rotknife',
    name: 'Rotknife',
    cost: 1,
    type: 'status',
    description: 'Deal 3 damage. Apply 3 poison.',
    effects: [
      { type: 'damage', amount: 3 },
      { type: 'poison', amount: 3 },
    ],
    unlock: { building: 'herbalHut', level: 2 },
    puzzleRoles: ['counter', 'setup'],
  },
  bitterCloud: {
    id: 'bitterCloud',
    name: 'Bitter Cloud',
    cost: 2,
    type: 'status',
    description: 'Apply 6 poison.',
    effects: [{ type: 'poison', amount: 6 }],
    unlock: { building: 'herbalHut', level: 2 },
    puzzleRoles: ['counter'],
  },
  brace: {
    id: 'brace',
    name: 'Brace',
    cost: 0,
    type: 'defense',
    description: 'Gain 3 block. Draw 1 card.',
    effects: [
      { type: 'block', amount: 3 },
      { type: 'draw', amount: 1 },
    ],
    puzzleRoles: ['counter', 'setup'],
  },
  markedBlow: {
    id: 'markedBlow',
    name: 'Marked Blow',
    cost: 1,
    type: 'attack',
    description: 'Deal 4 damage. Draw 1 card.',
    effects: [
      { type: 'damage', amount: 4 },
      { type: 'draw', amount: 1 },
    ],
    metaUnlockEmbers: 4,
    puzzleRoles: ['setup', 'finisher'],
  },
  cinderMark: {
    id: 'cinderMark',
    name: 'Cinder Mark',
    cost: 1,
    type: 'status',
    description: 'Expose: next damage this turn deals +5.',
    effects: [{ type: 'applyExposed', amount: 5 }],
    puzzleRoles: ['setup'],
  },
  brittleSlash: {
    id: 'brittleSlash',
    name: 'Brittle Slash',
    cost: 1,
    type: 'attack',
    description: 'Brittle: next damage ignores block. Deal 5.',
    effects: [{ type: 'markBrittle' }, { type: 'damage', amount: 5 }],
    puzzleRoles: ['counter', 'finisher'],
  },
  venomStrike: {
    id: 'venomStrike',
    name: 'Venom Strike',
    cost: 1,
    type: 'attack',
    description: 'Deal 4 damage. If the enemy is poisoned, heal 2.',
    effects: [{ type: 'damage', amount: 4, siphonIfPoisoned: 2 }],
    unlock: { building: 'herbalHut', level: 1 },
    metaUnlockEmbers: 10,
    puzzleRoles: ['counter', 'stabilizer'],
  },
  ashTap: {
    id: 'ashTap',
    name: 'Ash Tap',
    cost: 0,
    type: 'utility',
    description: 'Expose: next damage this turn deals +2. Draw 1.',
    effects: [
      { type: 'applyExposed', amount: 2 },
      { type: 'draw', amount: 1 },
    ],
    unlock: { building: 'watchtower', level: 1 },
    metaUnlockEmbers: 18,
    puzzleRoles: ['setup'],
  },
  emberSpark: {
    id: 'emberSpark',
    name: 'Ember Spark',
    cost: 1,
    type: 'status',
    description: 'Deal 3 damage. Apply 1 poison. Expose +2.',
    effects: [
      { type: 'damage', amount: 3 },
      { type: 'poison', amount: 1 },
      { type: 'applyExposed', amount: 2 },
    ],
    puzzleRoles: ['counter', 'setup', 'finisher'],
  },
};
