import type { EnemyDefinition } from '../types';

export const enemies: Record<string, EnemyDefinition> = {
  ashStalker: {
    id: 'ashStalker',
    name: 'Ash Stalker',
    maxHp: 22,
    role: 'Basic attacker',
    puzzleHint: 'Counter charged strikes by building enough block on telegraph turns.',
    intents: [
      { label: 'Circling… gathering ash', telegraphCharge: 3, puzzleObjective: 'counterBlock' },
      { label: 'Claw from the ash', damage: 6, damageUsesCharge: true, puzzleObjective: 'counterBlock' },
    ],
    rewards: { wood: 3, iron: 1 },
  },
  cinderGuard: {
    id: 'cinderGuard',
    name: 'Cinder Guard',
    maxHp: 28,
    role: 'Defender',
    puzzleHint: 'Break through guard stances by setting up and then finishing in the same turn.',
    intents: [
      { label: 'Brace for impact', telegraphCharge: 2, puzzleObjective: 'sequenceSetupFinisher' },
      { label: 'Shield bash', damage: 5, damageUsesCharge: true, puzzleObjective: 'sequenceSetupFinisher' },
      { label: 'Raise shield', block: 7, puzzleObjective: 'counterPierce' },
    ],
    rewards: { wood: 2, iron: 3 },
  },
  hollowSpitter: {
    id: 'hollowSpitter',
    name: 'Hollow Spitter',
    maxHp: 20,
    role: 'Inflictor',
    puzzleHint: 'Answer venom turns with poison pressure or mitigation before the bite lands.',
    intents: [
      { label: 'Gurgling…', telegraphCharge: 2, puzzleObjective: 'counterPoison' },
      { label: 'Spit poison', poison: 2, puzzleObjective: 'counterPoison' },
      { label: 'Bite from the hollow', damage: 7, damageUsesCharge: true, puzzleObjective: 'counterBlock' },
    ],
    rewards: { herbs: 3, wood: 1 },
  },
  graveMender: {
    id: 'graveMender',
    name: 'Grave Mender',
    maxHp: 24,
    role: 'Support',
    puzzleHint: 'Punish recovery windows with setup-then-finisher sequences.',
    intents: [
      { label: 'Leech for 4', damage: 4, puzzleObjective: 'counterBlock' },
      { label: 'Bone ward', block: 8, puzzleObjective: 'sequenceSetupFinisher' },
    ],
    rewards: { food: 3, herbs: 1 },
  },
  ashBulwark: {
    id: 'ashBulwark',
    name: 'Ash Bulwark',
    maxHp: 30,
    role: 'Bulwark',
    puzzleHint: 'Its armor cycles between charge and plating. Time setup into pierce windows.',
    intents: [
      { label: 'Braces behind cinder plate', block: 9, puzzleObjective: 'counterPierce' },
      { label: 'Banks furnace pressure', telegraphCharge: 3, puzzleObjective: 'counterBlock' },
      { label: 'Basalt slam', damage: 7, damageUsesCharge: true, puzzleObjective: 'sequenceSetupFinisher' },
    ],
    rewards: { iron: 2, wood: 2, food: 1 },
  },
  emberSeer: {
    id: 'emberSeer',
    name: 'Ember Seer',
    maxHp: 23,
    role: 'Hexer',
    puzzleHint: 'It alternates venom and burn pressure. Counter poison turns before the burst.',
    intents: [
      { label: 'Whispered ash omen', telegraphCharge: 2, puzzleObjective: 'counterPoison' },
      { label: 'Hex plume', poison: 2, puzzleObjective: 'counterPoison' },
      { label: 'Ember burst', damage: 8, damageUsesCharge: true, puzzleObjective: 'counterBlock' },
    ],
    rewards: { herbs: 2, wood: 2, iron: 1 },
  },
  sootReaver: {
    id: 'sootReaver',
    name: 'Soot Reaver',
    maxHp: 27,
    role: 'Skirmisher',
    puzzleHint: 'This raider feints, then bursts. Block first, sequence punish second.',
    intents: [
      { label: 'Cuts a shallow feint', damage: 4, puzzleObjective: 'counterBlock' },
      { label: 'Reaver flourish', telegraphCharge: 3, puzzleObjective: 'sequenceSetupFinisher' },
      { label: 'Soot lunge', damage: 6, damageUsesCharge: true, puzzleObjective: 'counterBlock' },
    ],
    rewards: { wood: 2, iron: 2, food: 1 },
  },
  wickHowler: {
    id: 'wickHowler',
    name: 'Wick Howler',
    maxHp: 25,
    role: 'Harrier',
    puzzleHint: 'It escalates venom over time. Meet poison counters early before momentum spikes.',
    intents: [
      { label: 'Howls through cinders', telegraphCharge: 2, puzzleObjective: 'counterPoison' },
      { label: 'Fanged vapor', poison: 2, puzzleObjective: 'counterPoison' },
      { label: 'Rake and retreat', damage: 6, puzzleObjective: 'counterBlock' },
    ],
    rewards: { herbs: 3, wood: 1, food: 1 },
  },
  kilnSentinel: {
    id: 'kilnSentinel',
    name: 'Kiln Sentinel',
    maxHp: 34,
    role: 'Bastion',
    puzzleHint: 'Its shell demands pierce answers. Setup-finisher timing cracks it open.',
    intents: [
      { label: 'Ceramic plating', block: 10, puzzleObjective: 'counterPierce' },
      { label: 'Internal pressure rise', telegraphCharge: 3, puzzleObjective: 'sequenceSetupFinisher' },
      { label: 'Kiln rupture', damage: 8, damageUsesCharge: true, puzzleObjective: 'counterBlock' },
    ],
    rewards: { iron: 3, wood: 2 },
  },
  ironWight: {
    id: 'ironWight',
    name: 'Iron Wight',
    maxHp: 42,
    role: 'Elite',
    puzzleHint: 'Alternate between surviving hammer telegraphs and piercing through plated turns.',
    intents: [
      { label: 'Draws back the hammer…', telegraphCharge: 4, puzzleObjective: 'counterBlock' },
      { label: 'Hammer fall', damage: 10, damageUsesCharge: true, puzzleObjective: 'counterBlock' },
      { label: 'Plate up', block: 10, puzzleObjective: 'counterPierce' },
    ],
    rewards: { iron: 5, relicShards: 1 },
  },
  pyreKnight: {
    id: 'pyreKnight',
    name: 'Pyre Knight',
    maxHp: 46,
    role: 'Elite',
    puzzleHint: 'This elite punishes greedy turns. Sequence setup-finisher plays between heavy telegraphs.',
    intents: [
      { label: 'Knightly feint', damage: 5, puzzleObjective: 'counterBlock' },
      { label: 'Raises pyre shield', block: 11, puzzleObjective: 'counterPierce' },
      { label: 'Ritual draw', telegraphCharge: 4, puzzleObjective: 'sequenceSetupFinisher' },
      { label: 'Pyre execution', damage: 9, damageUsesCharge: true, puzzleObjective: 'counterBlock' },
    ],
    rewards: { iron: 4, relicShards: 1, blueprintScraps: 1 },
  },
  duskTemplar: {
    id: 'duskTemplar',
    name: 'Dusk Templar',
    maxHp: 50,
    role: 'Elite',
    puzzleHint: 'A strict pattern fight: pierce shield turns, then survive punishing reprisals.',
    intents: [
      { label: 'Templar guard', block: 13, puzzleObjective: 'counterPierce' },
      { label: 'Measured strike', damage: 8, puzzleObjective: 'counterBlock' },
      { label: 'Dark rite', telegraphCharge: 5, puzzleObjective: 'sequenceSetupFinisher' },
      { label: 'Judgment cleave', damage: 10, damageUsesCharge: true, puzzleObjective: 'counterBlock' },
    ],
    rewards: { iron: 4, relicShards: 1, blueprintScraps: 1, food: 2 },
  },
  ashKnight: {
    id: 'ashKnight',
    name: 'The Ash Knight',
    maxHp: 58,
    role: 'Boss',
    puzzleHint: 'Read each phase: block storms, sequence burst windows, and poison counters.',
    intents: [
      { label: 'Rakes cinders into a storm', telegraphCharge: 5, puzzleObjective: 'counterBlock' },
      { label: 'Cinder cleave', damage: 6, damageUsesCharge: true, puzzleObjective: 'counterBlock' },
      { label: 'Black shield', block: 12, puzzleObjective: 'sequenceSetupFinisher' },
      { label: 'Punishing strike', damage: 14, puzzleObjective: 'counterPoison' },
    ],
    rewards: { wood: 8, iron: 5, relicShards: 1, blueprintScraps: 1 },
  },
};
